[package]
name = "shufang-sqlite"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
shufang-domain = { path = "../domain" }
shufang-application = { path = "../application" }
serde_json.workspace = true
rusqlite = { version = "0.38", features = ["bundled", "backup"] }
sha2 = "0.10"

[dev-dependencies]
tempfile = "3.26"
