import Foundation
import CryptoKit

enum StudyBackupError: LocalizedError {
    case invalid, unsupported, wrongAccount, tooLarge, missingBook(String), changedBook(String)
    var errorDescription: String? {
        switch self {
        case .invalid: return "备份不完整或校验失败，尚未恢复任何学习记录。"
        case .unsupported: return "该备份来自更新的书房版本，请先升级 App。"
        case .wrongAccount: return "此备份属于其他服务器或账户，请切换到原服务器并登录对应账户后恢复。"
        case .tooLarge: return "备份超过本机单次 512 MB 限制，请分别备份较小的学习集。"
        case .missingBook(let name): return "《\(name)》尚未完整下载，无法生成完整备份。请联网后重试。"
        case .changedBook(let name): return "《\(name)》的本机原文与备份不同。请选择“使用备份版本”恢复，避免卡片定位到错误原文。"
        }
    }
}

struct StudyBackupManifest: Codable {
    struct Entry: Codable {
        var path: String
        var bytes: Int
        var sha256: String
    }
    let format: String
    let version: Int
    let createdAt: Date
    let origin: String
    let userID: String
    let title: String
    let entries: [Entry]
}

/// A package uses regular files instead of embedding PDFs as base64 in JSON.
/// Paths are generated by the app and verified before reading any record.
struct StudyBackupArchive {
    static let maximumBytes = 512 * 1024 * 1024
    let manifest: StudyBackupManifest
    let payloads: [String: Data]
    init(title: String, origin: String, userID: String, payloads: [String: Data]) throws {
        guard payloads["study.json"] != nil, payloads.count <= 10_000,
              payloads.values.reduce(0, { $0 + $1.count }) <= Self.maximumBytes else { throw StudyBackupError.tooLarge }
        self.payloads = payloads
        manifest = StudyBackupManifest(format: "ShufangStudyBackup", version: 1, createdAt: Date(), origin: origin, userID: userID, title: title,
            entries: payloads.keys.sorted().map { path in
                .init(path: path, bytes: payloads[path]!.count, sha256: Self.hash(payloads[path]!))
            })
    }
    init(wrapper: FileWrapper) throws {
        guard wrapper.isDirectory, let metadata = wrapper.fileWrappers?["manifest.json"]?.regularFileContents,
              metadata.count < 2 * 1024 * 1024 else { throw StudyBackupError.invalid }
        manifest = try JSONDecoder().decode(StudyBackupManifest.self, from: metadata)
        guard manifest.format == "ShufangStudyBackup" else { throw StudyBackupError.invalid }
        guard manifest.version == 1 else { throw StudyBackupError.unsupported }
        guard manifest.entries.count <= 10_000, Set(manifest.entries.map(\.path)).count == manifest.entries.count else { throw StudyBackupError.invalid }
        var data: [String: Data] = [:]
        var total = 0
        for entry in manifest.entries {
            guard Self.validPath(entry.path), entry.bytes >= 0, entry.bytes <= Self.maximumBytes,
                  total <= Self.maximumBytes - entry.bytes else { throw StudyBackupError.tooLarge }
            total += entry.bytes
            var file = wrapper
            for part in entry.path.split(separator: "/") {
                guard file.isDirectory, let next = file.fileWrappers?[String(part)], !next.isSymbolicLink else { throw StudyBackupError.invalid }
                file = next
            }
            guard file.isRegularFile, let bytes = file.regularFileContents, bytes.count == entry.bytes,
                  Self.hash(bytes) == entry.sha256,
                  (!entry.path.hasPrefix("attachments/") || entry.path == "attachments/" + Self.hash(bytes)) else { throw StudyBackupError.invalid }
            data[entry.path] = bytes
        }
        guard data["study.json"] != nil else { throw StudyBackupError.invalid }
        let records = try JSONDecoder().decode([StudyRecord].self, from: data["study.json"]!)
        guard Set(records.map(\.key)).count == records.count else { throw StudyBackupError.invalid }
        for (hash, size) in try Self.referencedAttachments(records) {
            guard data["attachments/" + hash]?.count == size else { throw StudyBackupError.invalid }
        }
        payloads = data
    }
    func fileWrapper() throws -> FileWrapper {
        let root = FileWrapper(directoryWithFileWrappers: [:])
        for (path, data) in payloads {
            guard Self.validPath(path) else { throw StudyBackupError.invalid }
            let parts = path.split(separator: "/").map(String.init)
            var directory = root
            for part in parts.dropLast() {
                if let child = directory.fileWrappers?[part] { directory = child }
                else {
                    let child = FileWrapper(directoryWithFileWrappers: [:]); child.preferredFilename = part
                    directory.addFileWrapper(child); directory = child
                }
            }
            let file = FileWrapper(regularFileWithContents: data); file.preferredFilename = parts.last!
            directory.addFileWrapper(file)
        }
        let metadata = FileWrapper(regularFileWithContents: try JSONEncoder().encode(manifest))
        metadata.preferredFilename = "manifest.json"; root.addFileWrapper(metadata)
        return root
    }
    func validateScope(origin: String, userID: String) throws {
        guard ServerConfiguration.sameOrigin(origin, manifest.origin), userID == manifest.userID else { throw StudyBackupError.wrongAccount }
    }
    var records: [StudyRecord] { (try? JSONDecoder().decode([StudyRecord].self, from: payloads["study.json"] ?? Data())) ?? [] }
    var books: [(String, OfflineBookPackage)] {
        payloads.keys.filter { $0.hasPrefix("books/") && $0.hasSuffix("/package.json") }.sorted().compactMap { path in
            guard let data = payloads[path], let package = try? JSONDecoder().decode(OfflineBookPackage.self, from: data) else { return nil }
            return (String(path.dropLast("package.json".count)), package)
        }
    }
    func validatedBooks() throws -> [(String, OfflineBookPackage)] {
        let paths = payloads.keys.filter { $0.hasPrefix("books/") && $0.hasSuffix("/package.json") }
        let packages = books
        guard paths.count == packages.count, Set(packages.map { $0.1.book.id }).count == packages.count else { throw StudyBackupError.invalid }
        for (prefix, package) in packages {
            guard prefix == "books/" + Self.hash(Data(package.book.id.utf8)) + "/",
                  package.chapters.count == package.contents.count,
                  zip(package.chapters, package.contents).allSatisfy({ $0.0.id == $0.1.id }),
                  !package.contents.isEmpty || package.hasPDF else { throw StudyBackupError.invalid }
            if package.hasPDF {
                guard let pdf = payloads[prefix + "source.pdf"], pdf.starts(with: Data("%PDF".utf8)), pdf.count <= 256 * 1024 * 1024 else { throw StudyBackupError.invalid }
            }
        }
        return packages
    }
    static func referencedAttachments(_ records: [StudyRecord]) throws -> [String: Int] {
        var result: [String: Int] = [:]
        func insert(_ fields: [String: JSONValue]) throws {
            guard let hash = fields["sha256"]?.string, hash.count == 64,
                  hash.allSatisfy({ $0.isHexDigit && !$0.isUppercase }),
                  let size = fields["size"]?.number, size.isFinite, size >= 0,
                  size <= Double(256 * 1024 * 1024), size.rounded(.towardZero) == size,
                  result[hash] == nil || result[hash] == Int(size) else { throw StudyBackupError.invalid }
            result[hash] = Int(size)
        }
        func collect(_ value: JSONValue) throws {
            switch value {
            case .object(let fields):
                for key in ["$attachment", "$blob"] {
                    if let value = fields[key] {
                        guard let manifest = value.object else { throw StudyBackupError.invalid }
                        try insert(manifest)
                    }
                }
                for child in fields.values { try collect(child) }
            case .array(let values): for child in values { try collect(child) }
            default: break
            }
        }
        for record in records {
            try collect(.object(record.fields))
            if record.kind == "sources" { try insert(record.fields) }
        }
        return result
    }
    static func hash(_ data: Data) -> String { SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined() }
    private static func validPath(_ path: String) -> Bool {
        if path == "study.json" { return true }
        let parts = path.split(separator: "/", omittingEmptySubsequences: false)
        guard parts.allSatisfy({ !$0.isEmpty && $0 != "." && $0 != ".." && !$0.contains("\\") }), !path.hasPrefix("/") else { return false }
        if parts.count == 3 && parts[0] == "books" {
            return parts[1].count == 64 && parts[1].allSatisfy(\.isHexDigit) && ["package.json", "source.pdf"].contains(String(parts[2]))
        }
        return parts.count == 2 && parts[0] == "attachments" && parts[1].count == 64 && parts[1].allSatisfy(\.isHexDigit)
    }
}

