#include <jni.h>
#include "llama.h"
#include <vector>
#include <string>
#include <stdexcept>
#include <memory>

struct Engine {llama_model * model=nullptr;llama_context * context=nullptr;llama_sampler * sampler=nullptr;int generated=0;~Engine(){if(sampler)llama_sampler_free(sampler);if(context)llama_free(context);if(model)llama_model_free(model);}};
static void fail(JNIEnv * env,const char * message){env->ThrowNew(env->FindClass("java/lang/IllegalStateException"),message);}
static std::string bytes(JNIEnv *env,jbyteArray value){std::string result(env->GetArrayLength(value),'\0');env->GetByteArrayRegion(value,0,(jsize)result.size(),reinterpret_cast<jbyte*>(result.data()));return result;}
extern "C" JNIEXPORT jlong JNICALL Java_org_shufang_android_NativeLlm_open(JNIEnv *env,jobject,jbyteArray path){try{llama_backend_init();auto result=std::make_unique<Engine>();auto modelParams=llama_model_default_params();modelParams.n_gpu_layers=0;result->model=llama_model_load_from_file(bytes(env,path).c_str(),modelParams);if(!result->model)throw std::runtime_error("模型无法加载，请确认 GGUF 格式与设备内存");auto params=llama_context_default_params();params.n_ctx=2048;params.n_batch=256;params.n_threads=2;params.n_threads_batch=2;result->context=llama_init_from_model(result->model,params);if(!result->context)throw std::runtime_error("设备内存不足，无法创建模型上下文");result->sampler=llama_sampler_chain_init(llama_sampler_chain_default_params());llama_sampler_chain_add(result->sampler,llama_sampler_init_greedy());return reinterpret_cast<jlong>(result.release());}catch(const std::exception &e){fail(env,e.what());return 0;}}
extern "C" JNIEXPORT void JNICALL Java_org_shufang_android_NativeLlm_close(JNIEnv *,jobject,jlong pointer){delete reinterpret_cast<Engine*>(pointer);}
extern "C" JNIEXPORT void JNICALL Java_org_shufang_android_NativeLlm_prompt(JNIEnv *env,jobject,jlong pointer,jbyteArray input){try{auto *e=reinterpret_cast<Engine*>(pointer);if(!e)throw std::runtime_error("model_closed");const auto text=bytes(env,input);std::string formatted;llama_chat_message message={"user",text.c_str()};const char * tmpl=llama_model_chat_template(e->model,nullptr);int count=llama_chat_apply_template(tmpl,&message,1,true,nullptr,0);if(count<=0||count>128*1024)throw std::runtime_error("unsupported_model_chat_template");formatted.resize(count);llama_chat_apply_template(tmpl,&message,1,true,formatted.data(),count);const auto *vocab=llama_model_get_vocab(e->model);int tokens=llama_tokenize(vocab,formatted.data(),(int)formatted.size(),nullptr,0,true,true);if(tokens>=0||-tokens>1536)throw std::runtime_error("离线模型上下文过长，请缩小原文范围");std::vector<llama_token> values(-tokens);tokens=llama_tokenize(vocab,formatted.data(),(int)formatted.size(),values.data(),(int)values.size(),true,true);llama_memory_clear(llama_get_memory(e->context),true);llama_sampler_reset(e->sampler);e->generated=0;for(int offset=0;offset<tokens;offset+=256){if(llama_decode(e->context,llama_batch_get_one(values.data()+offset,std::min(256,tokens-offset)))!=0)throw std::runtime_error("model_prompt_failed");}}catch(const std::exception &e){fail(env,e.what());}}
extern "C" JNIEXPORT jbyteArray JNICALL Java_org_shufang_android_NativeLlm_next(JNIEnv *env,jobject,jlong pointer){try{auto *e=reinterpret_cast<Engine*>(pointer);if(!e)throw std::runtime_error("model_closed");if(e->generated++>=384)return nullptr;const auto *vocab=llama_model_get_vocab(e->model);const auto token=llama_sampler_sample(e->sampler,e->context,-1);if(llama_vocab_is_eog(vocab,token))return nullptr;llama_sampler_accept(e->sampler,token);std::vector<char> buffer(256);int length=llama_token_to_piece(vocab,token,buffer.data(),(int)buffer.size(),0,true);if(length<0){buffer.resize(-length);length=llama_token_to_piece(vocab,token,buffer.data(),(int)buffer.size(),0,true);}auto mutableToken=token;if(length<0||llama_decode(e->context,llama_batch_get_one(&mutableToken,1))!=0)throw std::runtime_error("model_decode_failed");auto result=env->NewByteArray(length);env->SetByteArrayRegion(result,0,length,reinterpret_cast<jbyte*>(buffer.data()));return result;}catch(const std::exception &e){fail(env,e.what());return nullptr;}}
