import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const app = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repository = path.dirname(app);
const executable = process.platform === "win32" ? "cargo.exe" : "cargo";
const installed = path.join(homedir(), ".cargo", "bin", executable);
const cargo =
  process.env.CARGO ?? (existsSync(installed) ? installed : executable);
// Containers supply the artifact built from the same checkout in their Rust stage.
// Source builds always compile; there is no silent stale-artifact fallback.
if (!process.env.SHUFANG_CORE_WASM) {
  const result = spawnSync(
    cargo,
    [
      "build",
      "--manifest-path",
      path.join(repository, "base/Cargo.toml"),
      "-p",
      "shufang-bindings",
      "--target",
      "wasm32-unknown-unknown",
      "--release",
      "--locked",
    ],
    { stdio: "inherit" }
  );
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}
const bytes = readFileSync(
  process.env.SHUFANG_CORE_WASM ??
    path.join(
      repository,
      "base/target/wasm32-unknown-unknown/release/shufang_bindings.wasm"
    )
);
const instance = new WebAssembly.Instance(new WebAssembly.Module(bytes));
if (instance.exports.core_abi_version() !== 1)
  throw new Error("unsupported_core_abi");
const directory = path.join(app, "generated");
mkdirSync(directory, { recursive: true });
writeFileSync(
  path.join(directory, "core-bytes.ts"),
  `// Generated by scripts/build-core.mjs. Do not edit.\nexport const coreBase64 = ${JSON.stringify(bytes.toString("base64"))};\n`
);
